[tool.poetry]
name = "flask-message-app"
version = "0.1.0"
description = "A simple Flask web application for sending and reading messages with JSON storage"
authors = ["Ivan Nazarov <nazarovv676@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.3.0"
gunicorn = "^21.2.0"

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

